version: '3.6'
services:
  sf-node-alice:
    image: 'functionland/sugarfunge-node:latest'
    restart: always
    network_mode: 'host'
    command: ["--alice", "--port=30334", "--ws-port=9944", "--prometheus-port=9091", "--ws-external", "--rpc-external", "--prometheus-external", "--rpc-cors", "all"]
    volumes:
      - ./rocksdb/alice:/root/.local/share/sugarfunge-node/chains/local_testnet/db/full
  sf-node-bob:
    image: 'functionland/sugarfunge-node:latest'
    restart: always
    network_mode: 'host'
    command: ["--bob", "--port=30335", "--ws-port=9945", "--ws-external", "--rpc-external", "--rpc-cors", "all", "--bootnodes", "/ip4/127.0.0.1/tcp/30334/p2p/12D3KooWGzN9EZLNkxEVeApishpq8d3pzChPmw9jQ9kra3csTAhk"]
    volumes:
      - ./rocksdb/bob:/root/.local/share/sugarfunge-node/chains/local_testnet/db/full
  sf-api:
    image: 'functionland/sugarfunge-api:latest'
    restart: always
    network_mode: 'host'
    command: ["-l", "http://0.0.0.0:4000", "-s", "ws://127.0.0.1:9944"]
  ipfs:
    image: 'ipfs/go-ipfs:v0.13.0'
    restart: always
    ports:
      - "4001:4001"
      - "8001:8080"
      - "5001:5001"
    volumes:
      - ./ipfs:/data/ipfs
  proof-engine:
    image: 'proof-engine:headless'
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    network_mode: 'host'
    environment:
      RUST_LOG: 'warn,fula_funge=info'
